import type { NextPage } from "next";
import Head from "next/head";
import HomeView from "../components/views/homeView";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Images/netflix_icon.png" />
      </Head>
      <HomeView />
    </>
  );
};

export default Home;
