import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useContext, useState } from "react";
import { AuthContext } from "../context";

const Home: NextPage = () => {
  const { authData, setAuthData } = useContext(AuthContext);
  const [inputValue, setinputValue] = useState("");

  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Images/netflix_icon.png" />
      </Head>

      <main className={styles.main}>
        <h1>Netflix</h1>
        <div>{authData?.username}</div>
        <div>
          <input
            type="text"
            value={inputValue}
            onChange={(e) => setinputValue(e.target.value)}
          />
          <button
            onClick={() =>
              setAuthData({
                ...authData,
                username: inputValue,
              })
            }
          >
            save
          </button>
        </div>
      </main>
    </div>
  );
};

export default Home;
